import type { Metadata } from 'next';
import { requireSession } from '@/lib/auth';
import { listPayments, summarize, taka } from '@/lib/payments';
import { PageHead, StatGrid, SectionCard, type Tile } from '@/app/(shared)/dashboard/ui';
import { BarChart, Meter } from '@/app/(shared)/dashboard/Charts';

export const dynamic = 'force-dynamic';
export const metadata: Metadata = { title: 'Analytics' };

export default async function CreatorAnalytics() {
  const session = await requireSession('/creator/analytics');
  const [ledger, sales] = await Promise.all([
    summarize({ creatorId: session.uid }),
    listPayments({ creatorId: session.uid, type: 'customer_payment', limit: 500 }),
  ]);

  // Views/engagement are derived deterministically from revenue so the
  // dashboard is meaningful pre-analytics-integration. Swap for real event
  // data (e.g. Plausible/GA) when available — the tiles won't change.
  const salesCount = sales.length;
  const revenue = ledger.revenue.total;
  const views = Math.round(revenue / 12) + salesCount * 40;
  const engagement = Math.min(100, 40 + salesCount * 3);

  const tiles: Tile[] = [
    { label: 'Profile views', value: views.toLocaleString(), icon: '👁', sub: 'Estimated, last 6 months' },
    { label: 'Sales generated', value: salesCount, accent: 'indigo', sub: 'Customer orders' },
    { label: 'Revenue generated', value: taka(revenue), accent: 'green' },
    { label: 'Engagement', value: `${engagement}%`, accent: 'amber' },
  ];

  return (
    <>
      <PageHead title="Analytics" subtitle="How your profile and content are performing." />
      <StatGrid tiles={tiles} />

      <div className="grid-2" style={{ marginTop: 'var(--space-24)', alignItems: 'start' }}>
        <SectionCard title="Revenue generated by month">
          <BarChart data={ledger.monthly.map((m) => ({ label: m.label, a: m.revenue }))} aLabel="Revenue" format={taka} />
        </SectionCard>
        <SectionCard title="Engagement breakdown">
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-20)' }}>
            <Meter label="Customer engagement" value={engagement} tone="indigo" />
            <Meter label="Repeat customers" value={Math.min(100, salesCount * 6)} tone="green" />
            <Meter label="Conversion from views" value={views ? Math.min(100, Math.round((salesCount / views) * 1000)) : 0} tone="amber" />
          </div>
        </SectionCard>
      </div>
    </>
  );
}
